### ISSUE TITLE
Disable transfer

### ISSUE THREAD

**Issue by nasiridrishi** [CzechPMDevs/SmallPlugins#5]
I am sorry sir but server disable transfer is not working for me .. is it for you?

**Comment by GamakCZ** [comment]
Is it @ImKyd work :D.

**Comment by GamakCZ** [comment]
The error is caused by pocketmine.

**Comment by GuyWhoDoThings** [comment]
Do you get any error in console?

**Comment by GamakCZ** [comment]
It does not work because pocketmine sends a closed window when the server is stopped.
